services:
    EuphoriaRaspberry.sworplus.listener:
        class: EuphoriaRaspberry\sworplus\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
        tags:
            - { name: event.listener }
